### PR TITLE
LITE-23776 Added support for meta information

### PR DESCRIPTION
**Pull request by maxipavlovic**

### CODE REVIEW

**Comment by jazz-jack** [comment]
Shouldn't we add some generic/default meta function? 
I guess just passing signal type in meta would be good step forward

**Comment by maxipavlovic** [comment]
> Shouldn't we add some generic/default meta function? I guess just passing signal type in meta would be good step forward

I don't think that we should do that in library terms, as signal type is present in TransportPayload anyway, so this would be excessive (same is true for correlation id for now, for example). Signal type is passed to `get_cqrs_meta`, so it could be done in some abstraction layer if it's needed.

**Review by gab832 — APPROVED** [review]

**Comment by jazz-jack** [comment]
> I don't think that we should do that in library terms, as signal type is present in TransportPayload anyway, so this would be excessive (same is true for correlation id for now, for example). Signal type is passed to `get_cqrs_meta`, so it could be done in some abstraction layer if it's needed.

don't we have a plan to deprecate `sync` flag in favour of `meta: {signal_type: ...}`? for me it looks more organic to move it to `meta`

**Comment by maxipavlovic** [comment]
I understood that I didn't add support for meta in replica side 🤷 , which makes this PR much less reasonable. Will fix today-tomorrow.

**Comment by jazz-jack** [comment]
> > > I don't think that we should do that in library terms, as signal type is present in TransportPayload anyway, so this would be excessive (same is true for correlation id for now, for example). Signal type is passed to `get_cqrs_meta`, so it could be done in some abstraction layer if it's needed.
> > 
> > 
> > don't we have a plan to deprecate `sync` flag in favour of `meta: {signal_type: ...}`? for me it looks more organic to move it to `meta`
> 
> Hm, haven't thought of that, thx 🤔
> 
> But thinking of that, I guess, that it' not the best idea. If we will look at `transport.rabbit_mq.RabbitMQTransport._get_produced_message_routing_key`, for example, we will find out that even other routes are used for sync, so this is a very important flag. We even sometimes have `SignalType.SYNC`. We could compare this to other options like `expire` or `retries`, which seem like better candidates for Meta, but even their inclusion is doubtful. Let's look from the perspective of Meta editing. Meta can be overridden from user perspective and we would need to have Meta of Meta to keep framework functioning, which seems excessive for me and harder for client to parse. Let's always consider meta just additional tooling for custom client purposes in library terms.

I'd agree that bug in master's meta function could harm data on (number of) replicas - it would be too powerful tool

**Review by d3rky — CHANGES_REQUESTED** [review]

**Review by d3rky — APPROVED** [review]

**Review by romeech — APPROVED** [review]

**Pull request merged**
